### ISSUE TITLE
Button Resize in Freq & Clock Window

### ISSUE THREAD

**Issue by Joe-K0OG** [bazineta/js8call#1]
Allan,

I like this latest commit. The buttons don't vertically stretch when resizing the top window. I think this is better (more pleasing) behavior.

73,
-Joe-

Later...

Well, I spoke too soon! I find the above to be true on Windows, but on Linux the buttons in the top "Frequency & Clock" window DO resize vertically. I double-checked, and am using the same source to build both (commit https://github.com/bazineta/js8call/commit/85844ee67b0e654dbcdd4cff9ce653631d908b3e). I tested under different styles ("windows" and "fusion") and get the same result: The buttons do vertically resize on Linux but not on Windows. Therefore, the inconsistency in behavior is platform-dependent, not style-dependent.

**Comment by bazineta** [comment]
I've experimented with setting the vertical on the buttons to 'fixed'; this will perhaps address the growth on Linux. I didn't see the problem on OSX, so I'm not able to replicate -- this change at least doesn't seem to cause any regression on OSX.

**Comment by Joe-K0OG** [comment]
Allan,

I built and tested on both Windows and Linux.  Windows functionality did not change, and on Linux the buttons are now a fixed size as on Windows and OSX.  

One *very minor* difference:  On Windows, the buttons and time & frequency fields are anchored to each other (their positions relative to each other vertically don't change when expanding the Freq & Clock window), yet on Linux, each set of buttons, frequency, and time "floats" so that when the window is expanded, the vertical space between each element expands.  In my opinion, it's not worth spending any time on, but if you know what to do to make the behavior consistent across platforms, and it doen't take more than about 30 seconds for you to do, then go ahead, otherwise, don't waste time on it.

73,
-Joe-
K0OG

**Comment by bazineta** [comment]
A screenshot of what you're seeing on Linux would be very helpful.

**Comment by Joe-K0OG** [comment]
Allan,

Yes, I should have done screenshots.

Minimum sized Freq & Clock window on my little Thinkpad x200 12" screen:
![image](https://github.com/user-attachments/assets/252a640e-6f61-45ef-91d5-4f0186be9f6d)

Here is a stretched Freq & Clock window,same laptop:
![image](https://github.com/user-attachments/assets/4da7388f-51f4-4cf3-a3b7-08097a8f9f73)

73,
-Joe-
K0OG

**Comment by bazineta** [comment]
Have pushed a change that might help. Shooting in the dark here, but logically, it makes sense.
